### ISSUE TITLE
Infinity Squared theme no longer supported

### ISSUE THREAD

**Issue by TRECpro** [YOURLS/awesome#142]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

Infinity Squared is no longer supported and should be removed from this list.

**Comment by ozh** [comment]
I think it's up to the user to decide if they'll use it or not.

**Comment by TRECpro** [comment]
It would really help to know at least which projects are under active development and maintenance. I think there are two ways this could be accomplished. Adding text after the project name with the version number it was last confirmed to work with would be great. Another option would be the date of its last release. A bot could be made to maintain either option.

**Comment by jarebear6expepjozn6rakjq5iczi3irqwphcvb** [comment]
@TRECpro It's pretty easy for a user to do their due diligence.  You're proposing an awful lot of overhead in the stead of you clicking a physical link, especially in the case of infinity, and determine it's development status.   At which point you would be able to establish whether you want to take on using it anyway, or pick a different one that matches your needs.
