### ISSUE TITLE
Listed plugins incompatible with latest YOURLS

### ISSUE THREAD

**Issue by RavanH** [YOURLS/awesome#154]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.9.2

### Description

The listed plugins APC Cache and YAPCache are not compatible with the latest version(s) of YOURLS. They are calling DB class properties that are not public anymore... Best to remove them?

I'm working on a replacement plugin that is compatible with APCu and YOURLS v1.9.2 on https://github.com/RavanH/APCu-Cache if anyone is interested...

**Comment by ozh** [comment]
Rather that unlist them, I'd rather link to an updated version when available, and leave to the user the decision of what to do when they come across a plugin that hasn't been updated in years. Most will work fine. Some will break.

Unlisting them would imply : 
- to maintain a compatibily list and test everything against every future YOURLS version, blargh
- to remove the opportunity that someone updates them when they see a need, like you're doing with APC (neat!)

(When your plugin is functional and tested, be sure to file a PR on Awesome YOURLS to get it listed!)

**Comment by RavanH** [comment]
Maybe add a warning or compatibility info? The plugins will cause an error 500 when installed... My alternative on https://github.com/RavanH/APCu-Cache appears to be working (testing phase) so far.
