### ISSUE TITLE
Generation QR Code in SVG, PDF, PNG, JPG locally

### ISSUE THREAD

**Issue by alexkolodko** [YOURLS/awesome#159]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I have created a plugin that generates a QR code directly on the site in a vector in svg format, and also allows you to download the code in SVG, PDF, PNG, JPG formats.
Try: [yourls-local-qr-code](https://github.com/alexkolodko/yourls-local-qr-code/)

### Motivation

I liked the idea of adding a `.qr` to a short link for generate code, but I wanted to have a vector code and not use Google services for this.

### Describe the solution

Demo gif in attach or you can see it on site — [qr.wayfinding.systems/a.qr](https://qr.wayfinding.systems/qr/?content=https://qr.wayfinding.systems/a)
![yourls-short-qr-x2](https://github.com/YOURLS/awesome/assets/3669694/54ff9339-84ec-4cd4-9d81-a22f53314c5a)

**Comment by LeoColomb** [comment]
Thanks for this issue @alexkolodko.
Don't hesitate to submit a pull request to add your plugin in the list.
