### ISSUE TITLE
Email Notify link is broken and maybe no longer works?

### ISSUE THREAD

**Issue by BillyCroan** [YOURLS/awesome#161]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.8.1

### Description

I tried to install Email Notify

your link in this list to it is broken but I searched and found https://github.com/tzkmx/Yourls-Email-Notify

and links stopped resolving. 

 errors in http log show it's trying to access a table called yourls_url, which does not exist
[Thu Jan 25 10:54:34.748948 2024] [php:error] [pid 31077] [client 2001:470:3943:0:ff26:12a:1072:c783:39988] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'Crn.li.yourls_url' doesn't exist in /var/www/Crn.li/user/plugins/email-notify/plugin.php:111\nStack trace:\n#0 /var/www/Crn.li/user/plugins/email-notify/plugin.php(111): mysqli->query()\n#1 /var/www/Crn.li/includes/functions-plugins.php(232): s22_email_notification()\n#2 /var/www/Crn.li/includes/functions-plugins.php(282): yourls_apply_filter()\n#3 /var/www/Crn.li/includes/functions.php(217): yourls_do_action()\n#4 /var/www/Crn.li/includes/functions.php(260): yourls_redirect()\n#5 /var/www/Crn.li/yourls-go.php(21): yourls_redirect_shorturl()\n#6 /var/www/Crn.li/yourls-loader.php(51): require_once('/var/www/Crn.li...')\n#7 {main}\n  thrown in /var/www/Crn.li/user/plugins/email-notify/plugin.php on line 111
[Thu Jan 25 10:54:42.968922 2024] [php:error] [pid 31094] [client 2001:470:3943:0:ff26:12a:1072:c783:58518] PHP Fatal error:  Uncaught mysqli_sql_exception: Table 'Crn.li.yourls_url' doesn't exist in /var/www/Crn.li/user/plugins/email-notify/plugin.php:111\nStack trace:\n#0 /var/www/Crn.li/user/plugins/email-notify/plugin.php(111): mysqli->query()\n#1 /var/www/Crn.li/includes/functions-plugins.php(232): s22_email_notification()\n#2 /var/www/Crn.li/includes/functions-plugins.php(282): yourls_apply_filter()\n#3 /var/www/Crn.li/includes/functions.php(217): yourls_do_action()\n#4 /var/www/Crn.li/includes/functions.php(260): yourls_redirect()\n#5 /var/www/Crn.li/yourls-go.php(21): yourls_redirect_shorturl()\n#6 /var/www/Crn.li/yourls-loader.php(51): require_once('/var/www/Crn.li...')\n#7 {main}\n  thrown in /var/www/Crn.li/user/plugins/email-notify/plugin.php on line 111

MariaDB [Crn.li]> show tables
    -> ;
+------------------+
| Tables_in_Crn.li |
+------------------+
| log              |
| options          |
| redirect         |
| url              |
+------------------+
4 rows in set (0.00 sec)

I've renamed yourls_url to yrl and yourls_log to log and it no longer errors but it doesn't work.

I'll work with tzkmx or fork it, but thought I'd report the broken link if nothing else.  you might update and add a note that its not working right now

### Expectation

links continue to resolve with plugin enabled

### Reproduction steps

install from https://github.com/tzkmx/Yourls-Email-Notify
test a link

### Context

expect to get emails to the admin email address when a link is used.

I'm opening this bug to update your list of links as it contains a broken link today.

**Comment by dgw** [comment]
The hardcoded table names are going to be a problem for many would-be users of that plugin code. https://yourls.org/docs/development/database-queries#the-ydb-object

If tzkmx or yourself do release an updated version, feel free to propose updating the broken link in the list here. Otherwise I'll try to remember to remove it if we don't hear about an updated version for a while.

**Comment by BillyCroan** [comment]
i got it working, sort of, but it's one hot mess and I don't feel like cleaning it up to the point I'd feel comfortable with my name on it publicly.  if someone out there wants it, message me at myfirstname@mylastname.org .  i don't want to bug @tzkmx  about it either.  looks like hes done a lot of repos but cooled off lately and he's got issue tracking off for this plugin anyway.  wouldn't surprise me if he didn't intend this to still be up.  I'd recommend strike it off the list for now or maybe point it to this issue thread.
