### ISSUE TITLE
The Emojis seems to be dead :(

### ISSUE THREAD

**Issue by SophiaAtkinson** [YOURLS/awesome#167]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Self troubleshooting

- [X] I've read the [documentation](https://yourls.org/) and made sure to follow it.
- [X] I've read the [troubleshooting first steps](https://docs.yourls.org/guide/troubleshooting/first-steps.html) and [frequent issues](https://docs.yourls.org/guide/troubleshooting/frequent-issues.html) guides.

### Version

1.19.2

### Description

The [Emojis](https://github.com/telepathics/yourls-emojis) plugin seems to have been removed from GitHub. I have the files still for anyone who may want it, just ask! But for now, I think it should be removed from the list ;(

### Expectation

N/A

### Reproduction steps

N/A

### Context

N/A

**Comment by ozh** [comment]
If you have the files, I advised you put them in a repo of your own, state that they are not yours and you're just mirroring, and mark the repo as read-only archive

**Comment by SophiaAtkinson** [comment]
Done! https://github.com/SophiaAtkinson/yourls-emojis

**Comment by ozh** [comment]
Thanks! URL updated
