### ISSUE TITLE
Multiple Short URLS to same Long URL

### ISSUE THREAD

**Issue by KensonPlayz** [YOURLS/awesome#173]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

I searched for 2-3 terms and could not find any useful answers. I'd like to set multiple short URLS to expand to the same long URL. For example: /news /blog both redirect to the blog.

### Motivation

This could help with the rare instance that someone wants to redirect 2-3 short URLs to the same long URL, for whatever reason, like similar spellings.

### Describe the solution

The ability to define multiple short urls via comma separation to the same long URL would be an easy way to do it.

**Comment by dgw** [comment]
This is a core feature. https://yourls.org/docs/guide/essentials/configuration#yourls_unique_urls

**Comment by KensonPlayz** [comment]
See, it wasn't a setting in the app so I wouldn't have known. I get extremely lost in documentation files, most of the time I can't find anything I need.

**Comment by TRECpro** [comment]
It would be great if there was a settings page to configure core features.

**Comment by dgw** [comment]
This is not the place to talk about it. We are in the issue tracker for the Awesome List of plugins and other add-ons. 😅
