### ISSUE TITLE
PHP SDK

### ISSUE THREAD

**Issue by cocochepeau** [YOURLS/awesome#177]
### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/YOURLS/.github/blob/main/CODE_OF_CONDUCT.md).

### Submission validity

- [X] This is not a personal support request, that should be posted on [discussions community](https://github.com/YOURLS/YOURLS/discussions).
- [X] I checked [current issues](https://github.com/YOURLS/YOURLS/issues) and this request isn't a duplicate of an existing issue, opened or closed.

### Summary

Hey there, I just created a basic PHP SDK package that talks to the API. Do you want it listed on  the list?

=> https://packagist.org/packages/cocochepeau/yourls-php-sdk

### Motivation

I needed this in personal projects.

**Comment by LeoColomb** [comment]
Thanks for opening this issue @cocochepeau.
That sounds good, don't hesitate to submit a PR with a link to your SDK 👍
I'm closing this issue as answered, but again, it's a yes.
